/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_grotesque_gecko_caff_parser_CAFF */

#ifndef _Included_hu_grotesque_gecko_caff_parser_CAFF
#define _Included_hu_grotesque_gecko_caff_parser_CAFF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_grotesque_gecko_caff_parser_CAFF
 * Method:    parseCaff
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_hu_grotesque_1gecko_caff_1parser_CAFF_parseCaff
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hu_grotesque_gecko_caff_parser_CAFF
 * Method:    freeCaff
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_hu_grotesque_1gecko_caff_1parser_CAFF_freeCaff
  (JNIEnv *, jobject, jlong);

/*
 * Class:     hu_grotesque_gecko_caff_parser_CAFF
 * Method:    previewCaff
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_hu_grotesque_1gecko_caff_1parser_CAFF_previewCaff
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
