name: Native CD

on:
  push:
    branches: master
  release:
    types: [published]
  pull_request:

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    env:
      working-directory: ./native

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Repository
        uses: docker/login-action@v1 
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/native.Dockerfile
          platforms: linux/amd64
          push: true
          tags: caff-store/native:latest